* arts-1-1-1179
* tests/Makefile.am:

Restructured the tests so that every test has its own directory. All
files required by a test should be available in that subdirectory.
A test directory can contain more than one test if they're closely
related (see tests/MonteCarlo).
The advantage of having self-contained test directories is that the
user can just copy one of the directories and use it as a starting
point for his own calculations (having all necessary input files
available without collecting them from other directories).

Convention for naming the tests is to have the testnames all start
with 'Test', followed by the name of the subdirectory they're in.
If there's more than one test in the subdirectory append a
descriptive text to the end of the testname. The controlfiles should
have the same name as the test + .arts.

Example for the MonteCarlo case: 

Test directory:              tests/MonteCarlo

Tests (named in testall.py): TestMonteCarloDataPrepare
			     TestMonteCarloGeneral
			     TestMonteCarloGeneralGaussian

Corresponding controlfiles:

tests/MonteCarlo/TestMonteCarloDataPrepare.arts
tests/MonteCarlo/TestMonteCarloGeneral.arts
tests/MonteCarlo/TestMonteCarloGeneralGaussian.arts

All tests have to be added to the "check" target in tests/Makefile.am
and the directories to TESTDIRS in the same Makefile.am.
Dependencies between tests can also be specified in there.

Tests can now run in parallel by default. E.g. if you have a computer
with 4 CPUs run: make -j4 check
To avoid cluttering when running tests in parallel, all output is
written to log files (TESTNAME.log).

* tests/testall.py:

Added the ability to run controlfiles from subdirectories.

Removed numbering from tests and give them clear names. 

* tests/data/, tests/*.arts: Removed.

* tests/{Abs,ClearSky,DISORT,DOIT,MonteCarlo}/: Added.


git-svn-id: https://www.sat.ltu.se/svn/rt/arts/trunk@5465 aaf1aab0-4228-0410-ad68-8dceda47f409

diff --git a/tests/Makefile.am b/tests/Makefile.am
--- a/tests/Makefile.am
+++ b/tests/Makefile.am
@@ -7,61 +7,44 @@
 # WITHOUT ANY WARRANTY, to the extent permitted by law; without even the
 # implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 
-SUBDIRS = data 
-check:
-	python testall.py -v
+SUBDIRS = 
 
-check-parallel: checkall
+TESTDIRS = Abs ClearSky DISORT DOIT MonteCarlo
 
-checkall: MonteCarloTests MiscTests
+TESTFILES = .arts .ac .xml .xml.bin
 
-MonteCarloTests: MonteCarloTest  MonteCarloTest2 \
-		 MonteCarloTest3 MonteCarloTest4
+check: \
+	TestMonteCarloDataPrepare \
+	TestMonteCarloGeneral \
+	TestMonteCarloGeneralGaussian \
+	TestDOIT \
+	TestClearSky \
+	TestAbs
 
-MiscTests: DoitTest ClearSkyTest AbsTest
+# Broken tests:
+#	TestMonteCarloSimple
+#	TestMonteCarloWithIncomingLookup
+#	TestDISORT
 
-DoitTest:
-	@if python testall.py $@ > $@.test.log 2>&1; then \
+#
+# Dependencies between tests
+#
+TestMonteCarloSimple: TestMonteCarloDataPrepare
+
+TestMonteCarloGeneral: TestMonteCarloDataPrepare
+
+TestMonteCarloGeneralGaussian: TestMonteCarloDataPrepare
+
+TestMonteCarloWithIncomingLookup: TestMonteCarloDataPrepare
+
+###############################################################
+
+Test%:
+	@if python testall.py $@ > $@.log 2>&1; then \
 		echo "$@ ok."; \
-		else echo "$@ failed. Find details in $@.test.log"; exit 1; fi
+		else echo "$@ failed. Find details in $@.log"; exit 1; fi
 
-ClearSkyTest:
-	@if python testall.py $@ > $@.test.log 2>&1; then \
-		echo "$@ ok."; \
-		else echo "$@ failed. Find details in $@.test.log"; exit 1; fi
+EXTRA_DIST = testall.py $(foreach dir, $(TESTDIRS), $(foreach extension,$(TESTFILES),$(wildcard $(dir)/*$(extension))))
 
-AbsTest:
-	@if python testall.py $@ > $@.test.log 2>&1; then \
-		echo "$@ ok."; \
-		else echo "$@ failed. Find details in $@.test.log"; exit 1; fi
-
-MonteCarloTest: MCDataPrepareTest
-	@if python testall.py $@ > $@.test.log 2>&1; then \
-		echo "$@ ok."; \
-		else echo "$@ failed. Find details in $@.test.log"; exit 1; fi
-
-MonteCarloTest2: MCDataPrepareTest
-	@if python testall.py $@ > $@.test.log 2>&1; then \
-		echo "$@ ok."; \
-		else echo "$@ failed. Find details in $@.test.log"; exit 1; fi
-
-MonteCarloTest3: MCDataPrepareTest
-	@if python testall.py $@ > $@.test.log 2>&1; then \
-		echo "$@ ok."; \
-		else echo "$@ failed. Find details in $@.test.log"; exit 1; fi
-
-MonteCarloTest4: MCDataPrepareTest
-	@if python testall.py $@ > $@.test.log 2>&1; then \
-		echo "$@ ok."; \
-		else echo "$@ failed. Find details in $@.test.log"; exit 1; fi
-
-MCDataPrepareTest:
-	@if python testall.py $@ > $@.test.log 2>&1; then \
-		echo "$@ ok."; \
-		else echo "$@ failed. Find details in $@.test.log"; exit 1; fi
-
-
-EXTRA_DIST = *.arts testall.py
-
-CLEANFILES = *.rep *.test.log
+CLEANFILES = *.log */*xml.generated* */*.rep
 
