* arts-1-1-1129
* tests/Makefile.am:

Added a check-parallel target so the testing framework can benefit
from multiple processor systems.
E.g. 'make -j4 check-parallel' to run on 4 processors.
To keep the output readable (as it might mix on parallel systems), it
is written to a log file for each test.

TODO: Refurbish/shorten the target rules.

* test/.cvsignore: Ignore log files.


git-svn-id: https://www.sat.ltu.se/svn/rt/arts/trunk@4805 aaf1aab0-4228-0410-ad68-8dceda47f409

diff --git a/tests/Makefile.am b/tests/Makefile.am
--- a/tests/Makefile.am
+++ b/tests/Makefile.am
@@ -7,11 +7,61 @@
 # WITHOUT ANY WARRANTY, to the extent permitted by law; without even the
 # implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 
-SUBDIRS = data
-
+SUBDIRS = data 
 check:
 	python testall.py -v
 
+check-parallel: checkall
+
+checkall: MonteCarloTests MiscTests
+
+MonteCarloTests: MonteCarloTest  MonteCarloTest2 \
+		 MonteCarloTest3 MonteCarloTest4
+
+MiscTests: DoitTest ClearSkyTest AbsTest
+
+DoitTest:
+	@if python testall.py $@ > $@.test.log 2>&1; then \
+		echo "$@ ok."; \
+		else echo "$@ failed. Find details in $@.test.log"; exit 1; fi
+
+ClearSkyTest:
+	@if python testall.py $@ > $@.test.log 2>&1; then \
+		echo "$@ ok."; \
+		else echo "$@ failed. Find details in $@.test.log"; exit 1; fi
+
+AbsTest:
+	@if python testall.py $@ > $@.test.log 2>&1; then \
+		echo "$@ ok."; \
+		else echo "$@ failed. Find details in $@.test.log"; exit 1; fi
+
+MonteCarloTest: MCDataPrepareTest
+	@if python testall.py $@ > $@.test.log 2>&1; then \
+		echo "$@ ok."; \
+		else echo "$@ failed. Find details in $@.test.log"; exit 1; fi
+
+MonteCarloTest2: MCDataPrepareTest
+	@if python testall.py $@ > $@.test.log 2>&1; then \
+		echo "$@ ok."; \
+		else echo "$@ failed. Find details in $@.test.log"; exit 1; fi
+
+MonteCarloTest3: MCDataPrepareTest
+	@if python testall.py $@ > $@.test.log 2>&1; then \
+		echo "$@ ok."; \
+		else echo "$@ failed. Find details in $@.test.log"; exit 1; fi
+
+MonteCarloTest4: MCDataPrepareTest
+	@if python testall.py $@ > $@.test.log 2>&1; then \
+		echo "$@ ok."; \
+		else echo "$@ failed. Find details in $@.test.log"; exit 1; fi
+
+MCDataPrepareTest:
+	@if python testall.py $@ > $@.test.log 2>&1; then \
+		echo "$@ ok."; \
+		else echo "$@ failed. Find details in $@.test.log"; exit 1; fi
+
+
 EXTRA_DIST = *.arts testall.py
 
-CLEANFILES = *.rep
+CLEANFILES = *.rep *.test.log
+
